// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WireApiDto } from "./WireApiDto";

export type InterpreterProvider = { id: string, name: string, description: string, isCurrent: boolean, baseUrl?: string, wireApi?: WireApiDto, envKey?: string, configured: boolean, isDefault: boolean, };
