name: 🎁 Feature Request
description: Propose a new feature for Open Interpreter
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Is Open Interpreter missing a feature that you'd like to see? Feel free to propose it here.

        Before you submit a feature:
        1. Search existing issues for similar features. If you find one, 👍 it rather than opening a new one.
        2. The Open Interpreter team will try to balance the varying needs of the community when prioritizing or rejecting new features. Not all features will be accepted. See [Contributing](../../docs/contributing.md) for more details.

  - type: input
    id: variant
    attributes:
      label: What part of Open Interpreter are you using?
      description: (e.g., interactive TUI, exec, installer, app server)
    validations:
      required: true
  - type: textarea
    id: feature
    attributes:
      label: What feature would you like to see?
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Additional information
      description: Is there anything else you think we should know?
