pub(crate) mod claude_code;
mod claude_code_prompt;
pub(crate) mod deepseek_tui;
pub(crate) mod guidance;
pub(crate) mod kimi_cli;
pub(crate) mod kimi_code;
pub(crate) mod little_coder;
pub(crate) mod mini_swe_agent;
pub(crate) mod minimal;
pub(crate) mod opencode;
pub(crate) mod pi;
pub(crate) mod qwen_code;
pub(crate) mod request;
pub(crate) mod routing;
pub(crate) mod session_skills;
pub(crate) mod swe_agent;
pub(crate) mod terminus_2;
pub(crate) mod zcode;
