// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageDetail } from "./ImageDetail";

/**
 * Structured content items that can be returned by a tool call.
 *
 * Most variants map directly to Responses API content. Harness adapters may
 * translate additional media variants into their provider-specific wire shape.
 */
export type FunctionCallOutputContentItem = { "type": "input_text", text: string, } | { "type": "input_image", image_url: string, detail?: ImageDetail, } | { "type": "input_video", video_url: string, id?: string, } | { "type": "encrypted_content", encrypted_content: string, };
